In [4]:
import numpy as np

In [5]:
a = np.array([1, 2, 3, 4, 5])

In [8]:
print(type(a))  #Type of the array
print(a.dtype)  #Data type of the array (can varry from PC to PC or from OS to OS)
print(a.size)   #Size of the array (element count)
print(a.shape)  #Shape of the array(will get size of array in first index in tuple and second index will contain rank in the array)
print(a.ndim)   #Dimentions of the array

<class 'numpy.ndarray'>
int32
5
(5,)
1


In [11]:
b = np.array([[1, 2], [3, 4]])

In [12]:
print(type(b))    #Type of the array
print(b.dtype)    #Data type of the array (can varry from PC to PC or from OS to OS)
print(b.size)     #Size of the array (element count)
print(b.shape)    #Shape of the array(will get size of array in first index in tuple and second index will contain rank in the array)
print(b.ndim)     #Dimentions of the array
print(b.itemsize) #Size(in bytes) of each element in array
print(b.data)     #Buffer data like memory address and much more (not usefull just for knowledge)

<class 'numpy.ndarray'>
int32
4
(2, 2)
2
4


Intrinsic Creation of an Array

In [24]:
print(np.zeros((3, 3)), end="\n\n")                 #This creates an array with 0 as their data
print(np.ones((3, 3)), end="\n\n")                  #This creates an array with 1 as their data
print(np.arange(0, 10), end="\n\n")                 #This creates an array with 0 to 9 continuous data
print(np.arange(0, 10, 3), end="\n\n")              #This creates an array with 0 to 9 and with a jump of 3
print(np.arange(0, 12).reshape(3, 4), end="\n\n")   #This will reshape the array with the rank and size given
print(np.linspace(0, 10, 9), end="\n\n")            #This will create an array with given space between numbers
print(np.random.random((4, 4)), end="\n\n")         #This will create an array with random data

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[0 1 2 3 4 5 6 7 8 9]

[0 3 6 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]

[[0.06389769 0.49836649 0.76573997 0.13856661]
 [0.03411835 0.57213625 0.07429396 0.52713645]
 [0.86069221 0.02424938 0.84732688 0.82160663]
 [0.23328551 0.16417598 0.47014378 0.10935562]]

